### ISSUE TITLE
Thanks and a question

### ISSUE THREAD

**Issue by renieh-leknuk** [ak5k/reafab#1]
Hey, I'm new to GitHub so I hope I'm at the right place for that, but:

thank you for that extension! I really wanted to build a custom hardware controller as a channel strip and use it with fab filter plugins.
I got a working Midi-Controller but couldn't figure the software out, at least the way I wanted it to behave. Collected Dust for a couple of years..

and now i just stumbled upon your work and almost had to laugh, because you nailed it so much! nice!

Now to my question ;)

I would love to use the controller with encoders and buttons for each of the plugins separately so I can place them in regard to the UI (in some form at least)
Is there a way to "get more encoders and buttons"? ;)

Thank you so much again!

**Comment by ak5k** [comment]
good to hear it has been useful.

currently i dont have any time to work on this, but in theory that kind of modifications are possible; and the source code is open. it would probably be easier to just extend the size of ReaFab, rather than implementing multiple ReaFab units each controlling different devices.

feel free to continue discussion at https://forum.cockos.com/showthread.php?t=261330
